/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.exercicekafka3.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CardSuit extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7539541065102788516L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CardSuit\",\"namespace\":\"com.example.exercicekafka3.model\",\"fields\":[{\"name\":\"spades\",\"type\":\"string\",\"doc\":\"the spades\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CardSuit> ENCODER =
      new BinaryMessageEncoder<CardSuit>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CardSuit> DECODER =
      new BinaryMessageDecoder<CardSuit>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CardSuit> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CardSuit> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CardSuit>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CardSuit to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CardSuit from a ByteBuffer. */
  public static CardSuit fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** the spades */
   private java.lang.CharSequence spades;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CardSuit() {}

  /**
   * All-args constructor.
   * @param spades the spades
   */
  public CardSuit(java.lang.CharSequence spades) {
    this.spades = spades;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return spades;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: spades = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'spades' field.
   * @return the spades
   */
  public java.lang.CharSequence getSpades() {
    return spades;
  }

  /**
   * Sets the value of the 'spades' field.
   * the spades
   * @param value the value to set.
   */
  public void setSpades(java.lang.CharSequence value) {
    this.spades = value;
  }

  /**
   * Creates a new CardSuit RecordBuilder.
   * @return A new CardSuit RecordBuilder
   */
  public static com.example.exercicekafka3.model.CardSuit.Builder newBuilder() {
    return new com.example.exercicekafka3.model.CardSuit.Builder();
  }

  /**
   * Creates a new CardSuit RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CardSuit RecordBuilder
   */
  public static com.example.exercicekafka3.model.CardSuit.Builder newBuilder(com.example.exercicekafka3.model.CardSuit.Builder other) {
    return new com.example.exercicekafka3.model.CardSuit.Builder(other);
  }

  /**
   * Creates a new CardSuit RecordBuilder by copying an existing CardSuit instance.
   * @param other The existing instance to copy.
   * @return A new CardSuit RecordBuilder
   */
  public static com.example.exercicekafka3.model.CardSuit.Builder newBuilder(com.example.exercicekafka3.model.CardSuit other) {
    return new com.example.exercicekafka3.model.CardSuit.Builder(other);
  }

  /**
   * RecordBuilder for CardSuit instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CardSuit>
    implements org.apache.avro.data.RecordBuilder<CardSuit> {

    /** the spades */
    private java.lang.CharSequence spades;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.exercicekafka3.model.CardSuit.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.spades)) {
        this.spades = data().deepCopy(fields()[0].schema(), other.spades);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CardSuit instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.exercicekafka3.model.CardSuit other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.spades)) {
        this.spades = data().deepCopy(fields()[0].schema(), other.spades);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'spades' field.
      * the spades
      * @return The value.
      */
    public java.lang.CharSequence getSpades() {
      return spades;
    }

    /**
      * Sets the value of the 'spades' field.
      * the spades
      * @param value The value of 'spades'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.CardSuit.Builder setSpades(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.spades = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'spades' field has been set.
      * the spades
      * @return True if the 'spades' field has been set, false otherwise.
      */
    public boolean hasSpades() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'spades' field.
      * the spades
      * @return This builder.
      */
    public com.example.exercicekafka3.model.CardSuit.Builder clearSpades() {
      spades = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CardSuit build() {
      try {
        CardSuit record = new CardSuit();
        record.spades = fieldSetFlags()[0] ? this.spades : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CardSuit>
    WRITER$ = (org.apache.avro.io.DatumWriter<CardSuit>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CardSuit>
    READER$ = (org.apache.avro.io.DatumReader<CardSuit>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
