/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.exercicekafka3.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DataFile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2665164167948939797L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataFile\",\"namespace\":\"com.example.exercicekafka3.model\",\"fields\":[{\"name\":\"serial_number\",\"type\":\"string\"},{\"name\":\"activity_date\",\"type\":\"string\"},{\"name\":\"facility_name\",\"type\":\"string\"},{\"name\":\"score\",\"type\":\"string\"},{\"name\":\"grade\",\"type\":\"string\"},{\"name\":\"service_code\",\"type\":\"string\"},{\"name\":\"service_description\",\"type\":\"string\"},{\"name\":\"employee_id\",\"type\":\"string\"},{\"name\":\"facility_address\",\"type\":\"string\"},{\"name\":\"facility_city\",\"type\":\"string\"},{\"name\":\"facility_id\",\"type\":\"string\"},{\"name\":\"facility_state\",\"type\":\"string\"},{\"name\":\"facility_zip\",\"type\":\"string\"},{\"name\":\"owner_id\",\"type\":\"string\"},{\"name\":\"owner_name\",\"type\":\"string\"},{\"name\":\"pe_description\",\"type\":\"string\"},{\"name\":\"program_element_pe\",\"type\":\"string\"},{\"name\":\"program_name\",\"type\":\"string\"},{\"name\":\"program_status\",\"type\":\"string\"},{\"name\":\"record_id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DataFile> ENCODER =
      new BinaryMessageEncoder<DataFile>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DataFile> DECODER =
      new BinaryMessageDecoder<DataFile>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DataFile> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DataFile> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DataFile>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DataFile to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DataFile from a ByteBuffer. */
  public static DataFile fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence serial_number;
   private java.lang.CharSequence activity_date;
   private java.lang.CharSequence facility_name;
   private java.lang.CharSequence score;
   private java.lang.CharSequence grade;
   private java.lang.CharSequence service_code;
   private java.lang.CharSequence service_description;
   private java.lang.CharSequence employee_id;
   private java.lang.CharSequence facility_address;
   private java.lang.CharSequence facility_city;
   private java.lang.CharSequence facility_id;
   private java.lang.CharSequence facility_state;
   private java.lang.CharSequence facility_zip;
   private java.lang.CharSequence owner_id;
   private java.lang.CharSequence owner_name;
   private java.lang.CharSequence pe_description;
   private java.lang.CharSequence program_element_pe;
   private java.lang.CharSequence program_name;
   private java.lang.CharSequence program_status;
   private java.lang.CharSequence record_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DataFile() {}

  /**
   * All-args constructor.
   * @param serial_number The new value for serial_number
   * @param activity_date The new value for activity_date
   * @param facility_name The new value for facility_name
   * @param score The new value for score
   * @param grade The new value for grade
   * @param service_code The new value for service_code
   * @param service_description The new value for service_description
   * @param employee_id The new value for employee_id
   * @param facility_address The new value for facility_address
   * @param facility_city The new value for facility_city
   * @param facility_id The new value for facility_id
   * @param facility_state The new value for facility_state
   * @param facility_zip The new value for facility_zip
   * @param owner_id The new value for owner_id
   * @param owner_name The new value for owner_name
   * @param pe_description The new value for pe_description
   * @param program_element_pe The new value for program_element_pe
   * @param program_name The new value for program_name
   * @param program_status The new value for program_status
   * @param record_id The new value for record_id
   */
  public DataFile(java.lang.CharSequence serial_number, java.lang.CharSequence activity_date, java.lang.CharSequence facility_name, java.lang.CharSequence score, java.lang.CharSequence grade, java.lang.CharSequence service_code, java.lang.CharSequence service_description, java.lang.CharSequence employee_id, java.lang.CharSequence facility_address, java.lang.CharSequence facility_city, java.lang.CharSequence facility_id, java.lang.CharSequence facility_state, java.lang.CharSequence facility_zip, java.lang.CharSequence owner_id, java.lang.CharSequence owner_name, java.lang.CharSequence pe_description, java.lang.CharSequence program_element_pe, java.lang.CharSequence program_name, java.lang.CharSequence program_status, java.lang.CharSequence record_id) {
    this.serial_number = serial_number;
    this.activity_date = activity_date;
    this.facility_name = facility_name;
    this.score = score;
    this.grade = grade;
    this.service_code = service_code;
    this.service_description = service_description;
    this.employee_id = employee_id;
    this.facility_address = facility_address;
    this.facility_city = facility_city;
    this.facility_id = facility_id;
    this.facility_state = facility_state;
    this.facility_zip = facility_zip;
    this.owner_id = owner_id;
    this.owner_name = owner_name;
    this.pe_description = pe_description;
    this.program_element_pe = program_element_pe;
    this.program_name = program_name;
    this.program_status = program_status;
    this.record_id = record_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return serial_number;
    case 1: return activity_date;
    case 2: return facility_name;
    case 3: return score;
    case 4: return grade;
    case 5: return service_code;
    case 6: return service_description;
    case 7: return employee_id;
    case 8: return facility_address;
    case 9: return facility_city;
    case 10: return facility_id;
    case 11: return facility_state;
    case 12: return facility_zip;
    case 13: return owner_id;
    case 14: return owner_name;
    case 15: return pe_description;
    case 16: return program_element_pe;
    case 17: return program_name;
    case 18: return program_status;
    case 19: return record_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: serial_number = (java.lang.CharSequence)value$; break;
    case 1: activity_date = (java.lang.CharSequence)value$; break;
    case 2: facility_name = (java.lang.CharSequence)value$; break;
    case 3: score = (java.lang.CharSequence)value$; break;
    case 4: grade = (java.lang.CharSequence)value$; break;
    case 5: service_code = (java.lang.CharSequence)value$; break;
    case 6: service_description = (java.lang.CharSequence)value$; break;
    case 7: employee_id = (java.lang.CharSequence)value$; break;
    case 8: facility_address = (java.lang.CharSequence)value$; break;
    case 9: facility_city = (java.lang.CharSequence)value$; break;
    case 10: facility_id = (java.lang.CharSequence)value$; break;
    case 11: facility_state = (java.lang.CharSequence)value$; break;
    case 12: facility_zip = (java.lang.CharSequence)value$; break;
    case 13: owner_id = (java.lang.CharSequence)value$; break;
    case 14: owner_name = (java.lang.CharSequence)value$; break;
    case 15: pe_description = (java.lang.CharSequence)value$; break;
    case 16: program_element_pe = (java.lang.CharSequence)value$; break;
    case 17: program_name = (java.lang.CharSequence)value$; break;
    case 18: program_status = (java.lang.CharSequence)value$; break;
    case 19: record_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'serial_number' field.
   * @return The value of the 'serial_number' field.
   */
  public java.lang.CharSequence getSerialNumber() {
    return serial_number;
  }

  /**
   * Sets the value of the 'serial_number' field.
   * @param value the value to set.
   */
  public void setSerialNumber(java.lang.CharSequence value) {
    this.serial_number = value;
  }

  /**
   * Gets the value of the 'activity_date' field.
   * @return The value of the 'activity_date' field.
   */
  public java.lang.CharSequence getActivityDate() {
    return activity_date;
  }

  /**
   * Sets the value of the 'activity_date' field.
   * @param value the value to set.
   */
  public void setActivityDate(java.lang.CharSequence value) {
    this.activity_date = value;
  }

  /**
   * Gets the value of the 'facility_name' field.
   * @return The value of the 'facility_name' field.
   */
  public java.lang.CharSequence getFacilityName() {
    return facility_name;
  }

  /**
   * Sets the value of the 'facility_name' field.
   * @param value the value to set.
   */
  public void setFacilityName(java.lang.CharSequence value) {
    this.facility_name = value;
  }

  /**
   * Gets the value of the 'score' field.
   * @return The value of the 'score' field.
   */
  public java.lang.CharSequence getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.CharSequence value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'grade' field.
   * @return The value of the 'grade' field.
   */
  public java.lang.CharSequence getGrade() {
    return grade;
  }

  /**
   * Sets the value of the 'grade' field.
   * @param value the value to set.
   */
  public void setGrade(java.lang.CharSequence value) {
    this.grade = value;
  }

  /**
   * Gets the value of the 'service_code' field.
   * @return The value of the 'service_code' field.
   */
  public java.lang.CharSequence getServiceCode() {
    return service_code;
  }

  /**
   * Sets the value of the 'service_code' field.
   * @param value the value to set.
   */
  public void setServiceCode(java.lang.CharSequence value) {
    this.service_code = value;
  }

  /**
   * Gets the value of the 'service_description' field.
   * @return The value of the 'service_description' field.
   */
  public java.lang.CharSequence getServiceDescription() {
    return service_description;
  }

  /**
   * Sets the value of the 'service_description' field.
   * @param value the value to set.
   */
  public void setServiceDescription(java.lang.CharSequence value) {
    this.service_description = value;
  }

  /**
   * Gets the value of the 'employee_id' field.
   * @return The value of the 'employee_id' field.
   */
  public java.lang.CharSequence getEmployeeId() {
    return employee_id;
  }

  /**
   * Sets the value of the 'employee_id' field.
   * @param value the value to set.
   */
  public void setEmployeeId(java.lang.CharSequence value) {
    this.employee_id = value;
  }

  /**
   * Gets the value of the 'facility_address' field.
   * @return The value of the 'facility_address' field.
   */
  public java.lang.CharSequence getFacilityAddress() {
    return facility_address;
  }

  /**
   * Sets the value of the 'facility_address' field.
   * @param value the value to set.
   */
  public void setFacilityAddress(java.lang.CharSequence value) {
    this.facility_address = value;
  }

  /**
   * Gets the value of the 'facility_city' field.
   * @return The value of the 'facility_city' field.
   */
  public java.lang.CharSequence getFacilityCity() {
    return facility_city;
  }

  /**
   * Sets the value of the 'facility_city' field.
   * @param value the value to set.
   */
  public void setFacilityCity(java.lang.CharSequence value) {
    this.facility_city = value;
  }

  /**
   * Gets the value of the 'facility_id' field.
   * @return The value of the 'facility_id' field.
   */
  public java.lang.CharSequence getFacilityId() {
    return facility_id;
  }

  /**
   * Sets the value of the 'facility_id' field.
   * @param value the value to set.
   */
  public void setFacilityId(java.lang.CharSequence value) {
    this.facility_id = value;
  }

  /**
   * Gets the value of the 'facility_state' field.
   * @return The value of the 'facility_state' field.
   */
  public java.lang.CharSequence getFacilityState() {
    return facility_state;
  }

  /**
   * Sets the value of the 'facility_state' field.
   * @param value the value to set.
   */
  public void setFacilityState(java.lang.CharSequence value) {
    this.facility_state = value;
  }

  /**
   * Gets the value of the 'facility_zip' field.
   * @return The value of the 'facility_zip' field.
   */
  public java.lang.CharSequence getFacilityZip() {
    return facility_zip;
  }

  /**
   * Sets the value of the 'facility_zip' field.
   * @param value the value to set.
   */
  public void setFacilityZip(java.lang.CharSequence value) {
    this.facility_zip = value;
  }

  /**
   * Gets the value of the 'owner_id' field.
   * @return The value of the 'owner_id' field.
   */
  public java.lang.CharSequence getOwnerId() {
    return owner_id;
  }

  /**
   * Sets the value of the 'owner_id' field.
   * @param value the value to set.
   */
  public void setOwnerId(java.lang.CharSequence value) {
    this.owner_id = value;
  }

  /**
   * Gets the value of the 'owner_name' field.
   * @return The value of the 'owner_name' field.
   */
  public java.lang.CharSequence getOwnerName() {
    return owner_name;
  }

  /**
   * Sets the value of the 'owner_name' field.
   * @param value the value to set.
   */
  public void setOwnerName(java.lang.CharSequence value) {
    this.owner_name = value;
  }

  /**
   * Gets the value of the 'pe_description' field.
   * @return The value of the 'pe_description' field.
   */
  public java.lang.CharSequence getPeDescription() {
    return pe_description;
  }

  /**
   * Sets the value of the 'pe_description' field.
   * @param value the value to set.
   */
  public void setPeDescription(java.lang.CharSequence value) {
    this.pe_description = value;
  }

  /**
   * Gets the value of the 'program_element_pe' field.
   * @return The value of the 'program_element_pe' field.
   */
  public java.lang.CharSequence getProgramElementPe() {
    return program_element_pe;
  }

  /**
   * Sets the value of the 'program_element_pe' field.
   * @param value the value to set.
   */
  public void setProgramElementPe(java.lang.CharSequence value) {
    this.program_element_pe = value;
  }

  /**
   * Gets the value of the 'program_name' field.
   * @return The value of the 'program_name' field.
   */
  public java.lang.CharSequence getProgramName() {
    return program_name;
  }

  /**
   * Sets the value of the 'program_name' field.
   * @param value the value to set.
   */
  public void setProgramName(java.lang.CharSequence value) {
    this.program_name = value;
  }

  /**
   * Gets the value of the 'program_status' field.
   * @return The value of the 'program_status' field.
   */
  public java.lang.CharSequence getProgramStatus() {
    return program_status;
  }

  /**
   * Sets the value of the 'program_status' field.
   * @param value the value to set.
   */
  public void setProgramStatus(java.lang.CharSequence value) {
    this.program_status = value;
  }

  /**
   * Gets the value of the 'record_id' field.
   * @return The value of the 'record_id' field.
   */
  public java.lang.CharSequence getRecordId() {
    return record_id;
  }

  /**
   * Sets the value of the 'record_id' field.
   * @param value the value to set.
   */
  public void setRecordId(java.lang.CharSequence value) {
    this.record_id = value;
  }

  /**
   * Creates a new DataFile RecordBuilder.
   * @return A new DataFile RecordBuilder
   */
  public static com.example.exercicekafka3.model.DataFile.Builder newBuilder() {
    return new com.example.exercicekafka3.model.DataFile.Builder();
  }

  /**
   * Creates a new DataFile RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DataFile RecordBuilder
   */
  public static com.example.exercicekafka3.model.DataFile.Builder newBuilder(com.example.exercicekafka3.model.DataFile.Builder other) {
    return new com.example.exercicekafka3.model.DataFile.Builder(other);
  }

  /**
   * Creates a new DataFile RecordBuilder by copying an existing DataFile instance.
   * @param other The existing instance to copy.
   * @return A new DataFile RecordBuilder
   */
  public static com.example.exercicekafka3.model.DataFile.Builder newBuilder(com.example.exercicekafka3.model.DataFile other) {
    return new com.example.exercicekafka3.model.DataFile.Builder(other);
  }

  /**
   * RecordBuilder for DataFile instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataFile>
    implements org.apache.avro.data.RecordBuilder<DataFile> {

    private java.lang.CharSequence serial_number;
    private java.lang.CharSequence activity_date;
    private java.lang.CharSequence facility_name;
    private java.lang.CharSequence score;
    private java.lang.CharSequence grade;
    private java.lang.CharSequence service_code;
    private java.lang.CharSequence service_description;
    private java.lang.CharSequence employee_id;
    private java.lang.CharSequence facility_address;
    private java.lang.CharSequence facility_city;
    private java.lang.CharSequence facility_id;
    private java.lang.CharSequence facility_state;
    private java.lang.CharSequence facility_zip;
    private java.lang.CharSequence owner_id;
    private java.lang.CharSequence owner_name;
    private java.lang.CharSequence pe_description;
    private java.lang.CharSequence program_element_pe;
    private java.lang.CharSequence program_name;
    private java.lang.CharSequence program_status;
    private java.lang.CharSequence record_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.exercicekafka3.model.DataFile.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.serial_number)) {
        this.serial_number = data().deepCopy(fields()[0].schema(), other.serial_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.activity_date)) {
        this.activity_date = data().deepCopy(fields()[1].schema(), other.activity_date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.facility_name)) {
        this.facility_name = data().deepCopy(fields()[2].schema(), other.facility_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.score)) {
        this.score = data().deepCopy(fields()[3].schema(), other.score);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.grade)) {
        this.grade = data().deepCopy(fields()[4].schema(), other.grade);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.service_code)) {
        this.service_code = data().deepCopy(fields()[5].schema(), other.service_code);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.service_description)) {
        this.service_description = data().deepCopy(fields()[6].schema(), other.service_description);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.employee_id)) {
        this.employee_id = data().deepCopy(fields()[7].schema(), other.employee_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.facility_address)) {
        this.facility_address = data().deepCopy(fields()[8].schema(), other.facility_address);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.facility_city)) {
        this.facility_city = data().deepCopy(fields()[9].schema(), other.facility_city);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.facility_id)) {
        this.facility_id = data().deepCopy(fields()[10].schema(), other.facility_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.facility_state)) {
        this.facility_state = data().deepCopy(fields()[11].schema(), other.facility_state);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.facility_zip)) {
        this.facility_zip = data().deepCopy(fields()[12].schema(), other.facility_zip);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.owner_id)) {
        this.owner_id = data().deepCopy(fields()[13].schema(), other.owner_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.owner_name)) {
        this.owner_name = data().deepCopy(fields()[14].schema(), other.owner_name);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.pe_description)) {
        this.pe_description = data().deepCopy(fields()[15].schema(), other.pe_description);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.program_element_pe)) {
        this.program_element_pe = data().deepCopy(fields()[16].schema(), other.program_element_pe);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.program_name)) {
        this.program_name = data().deepCopy(fields()[17].schema(), other.program_name);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.program_status)) {
        this.program_status = data().deepCopy(fields()[18].schema(), other.program_status);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.record_id)) {
        this.record_id = data().deepCopy(fields()[19].schema(), other.record_id);
        fieldSetFlags()[19] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DataFile instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.exercicekafka3.model.DataFile other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.serial_number)) {
        this.serial_number = data().deepCopy(fields()[0].schema(), other.serial_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.activity_date)) {
        this.activity_date = data().deepCopy(fields()[1].schema(), other.activity_date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.facility_name)) {
        this.facility_name = data().deepCopy(fields()[2].schema(), other.facility_name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.score)) {
        this.score = data().deepCopy(fields()[3].schema(), other.score);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.grade)) {
        this.grade = data().deepCopy(fields()[4].schema(), other.grade);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.service_code)) {
        this.service_code = data().deepCopy(fields()[5].schema(), other.service_code);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.service_description)) {
        this.service_description = data().deepCopy(fields()[6].schema(), other.service_description);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.employee_id)) {
        this.employee_id = data().deepCopy(fields()[7].schema(), other.employee_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.facility_address)) {
        this.facility_address = data().deepCopy(fields()[8].schema(), other.facility_address);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.facility_city)) {
        this.facility_city = data().deepCopy(fields()[9].schema(), other.facility_city);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.facility_id)) {
        this.facility_id = data().deepCopy(fields()[10].schema(), other.facility_id);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.facility_state)) {
        this.facility_state = data().deepCopy(fields()[11].schema(), other.facility_state);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.facility_zip)) {
        this.facility_zip = data().deepCopy(fields()[12].schema(), other.facility_zip);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.owner_id)) {
        this.owner_id = data().deepCopy(fields()[13].schema(), other.owner_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.owner_name)) {
        this.owner_name = data().deepCopy(fields()[14].schema(), other.owner_name);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.pe_description)) {
        this.pe_description = data().deepCopy(fields()[15].schema(), other.pe_description);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.program_element_pe)) {
        this.program_element_pe = data().deepCopy(fields()[16].schema(), other.program_element_pe);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.program_name)) {
        this.program_name = data().deepCopy(fields()[17].schema(), other.program_name);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.program_status)) {
        this.program_status = data().deepCopy(fields()[18].schema(), other.program_status);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.record_id)) {
        this.record_id = data().deepCopy(fields()[19].schema(), other.record_id);
        fieldSetFlags()[19] = true;
      }
    }

    /**
      * Gets the value of the 'serial_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getSerialNumber() {
      return serial_number;
    }

    /**
      * Sets the value of the 'serial_number' field.
      * @param value The value of 'serial_number'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setSerialNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.serial_number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'serial_number' field has been set.
      * @return True if the 'serial_number' field has been set, false otherwise.
      */
    public boolean hasSerialNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'serial_number' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearSerialNumber() {
      serial_number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'activity_date' field.
      * @return The value.
      */
    public java.lang.CharSequence getActivityDate() {
      return activity_date;
    }

    /**
      * Sets the value of the 'activity_date' field.
      * @param value The value of 'activity_date'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setActivityDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.activity_date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'activity_date' field has been set.
      * @return True if the 'activity_date' field has been set, false otherwise.
      */
    public boolean hasActivityDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'activity_date' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearActivityDate() {
      activity_date = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'facility_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityName() {
      return facility_name;
    }

    /**
      * Sets the value of the 'facility_name' field.
      * @param value The value of 'facility_name'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setFacilityName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.facility_name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'facility_name' field has been set.
      * @return True if the 'facility_name' field has been set, false otherwise.
      */
    public boolean hasFacilityName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'facility_name' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearFacilityName() {
      facility_name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'score' field.
      * @return The value.
      */
    public java.lang.CharSequence getScore() {
      return score;
    }

    /**
      * Sets the value of the 'score' field.
      * @param value The value of 'score'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setScore(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.score = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'score' field has been set.
      * @return True if the 'score' field has been set, false otherwise.
      */
    public boolean hasScore() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'score' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearScore() {
      score = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'grade' field.
      * @return The value.
      */
    public java.lang.CharSequence getGrade() {
      return grade;
    }

    /**
      * Sets the value of the 'grade' field.
      * @param value The value of 'grade'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setGrade(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.grade = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'grade' field has been set.
      * @return True if the 'grade' field has been set, false otherwise.
      */
    public boolean hasGrade() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'grade' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearGrade() {
      grade = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'service_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceCode() {
      return service_code;
    }

    /**
      * Sets the value of the 'service_code' field.
      * @param value The value of 'service_code'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setServiceCode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.service_code = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'service_code' field has been set.
      * @return True if the 'service_code' field has been set, false otherwise.
      */
    public boolean hasServiceCode() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'service_code' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearServiceCode() {
      service_code = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'service_description' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceDescription() {
      return service_description;
    }

    /**
      * Sets the value of the 'service_description' field.
      * @param value The value of 'service_description'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setServiceDescription(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.service_description = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'service_description' field has been set.
      * @return True if the 'service_description' field has been set, false otherwise.
      */
    public boolean hasServiceDescription() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'service_description' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearServiceDescription() {
      service_description = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'employee_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmployeeId() {
      return employee_id;
    }

    /**
      * Sets the value of the 'employee_id' field.
      * @param value The value of 'employee_id'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setEmployeeId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.employee_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'employee_id' field has been set.
      * @return True if the 'employee_id' field has been set, false otherwise.
      */
    public boolean hasEmployeeId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'employee_id' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearEmployeeId() {
      employee_id = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'facility_address' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityAddress() {
      return facility_address;
    }

    /**
      * Sets the value of the 'facility_address' field.
      * @param value The value of 'facility_address'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setFacilityAddress(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.facility_address = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'facility_address' field has been set.
      * @return True if the 'facility_address' field has been set, false otherwise.
      */
    public boolean hasFacilityAddress() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'facility_address' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearFacilityAddress() {
      facility_address = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'facility_city' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityCity() {
      return facility_city;
    }

    /**
      * Sets the value of the 'facility_city' field.
      * @param value The value of 'facility_city'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setFacilityCity(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.facility_city = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'facility_city' field has been set.
      * @return True if the 'facility_city' field has been set, false otherwise.
      */
    public boolean hasFacilityCity() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'facility_city' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearFacilityCity() {
      facility_city = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'facility_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityId() {
      return facility_id;
    }

    /**
      * Sets the value of the 'facility_id' field.
      * @param value The value of 'facility_id'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setFacilityId(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.facility_id = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'facility_id' field has been set.
      * @return True if the 'facility_id' field has been set, false otherwise.
      */
    public boolean hasFacilityId() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'facility_id' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearFacilityId() {
      facility_id = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'facility_state' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityState() {
      return facility_state;
    }

    /**
      * Sets the value of the 'facility_state' field.
      * @param value The value of 'facility_state'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setFacilityState(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.facility_state = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'facility_state' field has been set.
      * @return True if the 'facility_state' field has been set, false otherwise.
      */
    public boolean hasFacilityState() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'facility_state' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearFacilityState() {
      facility_state = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'facility_zip' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityZip() {
      return facility_zip;
    }

    /**
      * Sets the value of the 'facility_zip' field.
      * @param value The value of 'facility_zip'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setFacilityZip(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.facility_zip = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'facility_zip' field has been set.
      * @return True if the 'facility_zip' field has been set, false otherwise.
      */
    public boolean hasFacilityZip() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'facility_zip' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearFacilityZip() {
      facility_zip = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getOwnerId() {
      return owner_id;
    }

    /**
      * Sets the value of the 'owner_id' field.
      * @param value The value of 'owner_id'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setOwnerId(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.owner_id = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'owner_id' field has been set.
      * @return True if the 'owner_id' field has been set, false otherwise.
      */
    public boolean hasOwnerId() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'owner_id' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearOwnerId() {
      owner_id = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getOwnerName() {
      return owner_name;
    }

    /**
      * Sets the value of the 'owner_name' field.
      * @param value The value of 'owner_name'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setOwnerName(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.owner_name = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'owner_name' field has been set.
      * @return True if the 'owner_name' field has been set, false otherwise.
      */
    public boolean hasOwnerName() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'owner_name' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearOwnerName() {
      owner_name = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'pe_description' field.
      * @return The value.
      */
    public java.lang.CharSequence getPeDescription() {
      return pe_description;
    }

    /**
      * Sets the value of the 'pe_description' field.
      * @param value The value of 'pe_description'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setPeDescription(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.pe_description = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'pe_description' field has been set.
      * @return True if the 'pe_description' field has been set, false otherwise.
      */
    public boolean hasPeDescription() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'pe_description' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearPeDescription() {
      pe_description = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'program_element_pe' field.
      * @return The value.
      */
    public java.lang.CharSequence getProgramElementPe() {
      return program_element_pe;
    }

    /**
      * Sets the value of the 'program_element_pe' field.
      * @param value The value of 'program_element_pe'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setProgramElementPe(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.program_element_pe = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'program_element_pe' field has been set.
      * @return True if the 'program_element_pe' field has been set, false otherwise.
      */
    public boolean hasProgramElementPe() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'program_element_pe' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearProgramElementPe() {
      program_element_pe = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'program_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getProgramName() {
      return program_name;
    }

    /**
      * Sets the value of the 'program_name' field.
      * @param value The value of 'program_name'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setProgramName(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.program_name = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'program_name' field has been set.
      * @return True if the 'program_name' field has been set, false otherwise.
      */
    public boolean hasProgramName() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'program_name' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearProgramName() {
      program_name = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'program_status' field.
      * @return The value.
      */
    public java.lang.CharSequence getProgramStatus() {
      return program_status;
    }

    /**
      * Sets the value of the 'program_status' field.
      * @param value The value of 'program_status'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setProgramStatus(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.program_status = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'program_status' field has been set.
      * @return True if the 'program_status' field has been set, false otherwise.
      */
    public boolean hasProgramStatus() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'program_status' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearProgramStatus() {
      program_status = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'record_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getRecordId() {
      return record_id;
    }

    /**
      * Sets the value of the 'record_id' field.
      * @param value The value of 'record_id'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder setRecordId(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.record_id = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'record_id' field has been set.
      * @return True if the 'record_id' field has been set, false otherwise.
      */
    public boolean hasRecordId() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'record_id' field.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.DataFile.Builder clearRecordId() {
      record_id = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DataFile build() {
      try {
        DataFile record = new DataFile();
        record.serial_number = fieldSetFlags()[0] ? this.serial_number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.activity_date = fieldSetFlags()[1] ? this.activity_date : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.facility_name = fieldSetFlags()[2] ? this.facility_name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.score = fieldSetFlags()[3] ? this.score : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.grade = fieldSetFlags()[4] ? this.grade : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.service_code = fieldSetFlags()[5] ? this.service_code : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.service_description = fieldSetFlags()[6] ? this.service_description : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.employee_id = fieldSetFlags()[7] ? this.employee_id : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.facility_address = fieldSetFlags()[8] ? this.facility_address : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.facility_city = fieldSetFlags()[9] ? this.facility_city : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.facility_id = fieldSetFlags()[10] ? this.facility_id : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.facility_state = fieldSetFlags()[11] ? this.facility_state : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.facility_zip = fieldSetFlags()[12] ? this.facility_zip : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.owner_id = fieldSetFlags()[13] ? this.owner_id : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.owner_name = fieldSetFlags()[14] ? this.owner_name : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.pe_description = fieldSetFlags()[15] ? this.pe_description : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.program_element_pe = fieldSetFlags()[16] ? this.program_element_pe : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.program_name = fieldSetFlags()[17] ? this.program_name : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.program_status = fieldSetFlags()[18] ? this.program_status : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.record_id = fieldSetFlags()[19] ? this.record_id : (java.lang.CharSequence) defaultValue(fields()[19]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DataFile>
    WRITER$ = (org.apache.avro.io.DatumWriter<DataFile>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DataFile>
    READER$ = (org.apache.avro.io.DatumReader<DataFile>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
