/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.exercicekafka3.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SimpleCard extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9139524777084862413L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SimpleCard\",\"namespace\":\"com.example.exercicekafka3.model\",\"fields\":[{\"name\":\"spades\",\"type\":\"string\",\"doc\":\"the spades\"},{\"name\":\"ace\",\"type\":\"string\",\"doc\":\"the card number\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SimpleCard> ENCODER =
      new BinaryMessageEncoder<SimpleCard>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SimpleCard> DECODER =
      new BinaryMessageDecoder<SimpleCard>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SimpleCard> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SimpleCard> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SimpleCard>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SimpleCard to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SimpleCard from a ByteBuffer. */
  public static SimpleCard fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** the spades */
   private java.lang.CharSequence spades;
  /** the card number */
   private java.lang.CharSequence ace;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SimpleCard() {}

  /**
   * All-args constructor.
   * @param spades the spades
   * @param ace the card number
   */
  public SimpleCard(java.lang.CharSequence spades, java.lang.CharSequence ace) {
    this.spades = spades;
    this.ace = ace;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return spades;
    case 1: return ace;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: spades = (java.lang.CharSequence)value$; break;
    case 1: ace = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'spades' field.
   * @return the spades
   */
  public java.lang.CharSequence getSpades() {
    return spades;
  }

  /**
   * Sets the value of the 'spades' field.
   * the spades
   * @param value the value to set.
   */
  public void setSpades(java.lang.CharSequence value) {
    this.spades = value;
  }

  /**
   * Gets the value of the 'ace' field.
   * @return the card number
   */
  public java.lang.CharSequence getAce() {
    return ace;
  }

  /**
   * Sets the value of the 'ace' field.
   * the card number
   * @param value the value to set.
   */
  public void setAce(java.lang.CharSequence value) {
    this.ace = value;
  }

  /**
   * Creates a new SimpleCard RecordBuilder.
   * @return A new SimpleCard RecordBuilder
   */
  public static com.example.exercicekafka3.model.SimpleCard.Builder newBuilder() {
    return new com.example.exercicekafka3.model.SimpleCard.Builder();
  }

  /**
   * Creates a new SimpleCard RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SimpleCard RecordBuilder
   */
  public static com.example.exercicekafka3.model.SimpleCard.Builder newBuilder(com.example.exercicekafka3.model.SimpleCard.Builder other) {
    return new com.example.exercicekafka3.model.SimpleCard.Builder(other);
  }

  /**
   * Creates a new SimpleCard RecordBuilder by copying an existing SimpleCard instance.
   * @param other The existing instance to copy.
   * @return A new SimpleCard RecordBuilder
   */
  public static com.example.exercicekafka3.model.SimpleCard.Builder newBuilder(com.example.exercicekafka3.model.SimpleCard other) {
    return new com.example.exercicekafka3.model.SimpleCard.Builder(other);
  }

  /**
   * RecordBuilder for SimpleCard instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SimpleCard>
    implements org.apache.avro.data.RecordBuilder<SimpleCard> {

    /** the spades */
    private java.lang.CharSequence spades;
    /** the card number */
    private java.lang.CharSequence ace;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.exercicekafka3.model.SimpleCard.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.spades)) {
        this.spades = data().deepCopy(fields()[0].schema(), other.spades);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ace)) {
        this.ace = data().deepCopy(fields()[1].schema(), other.ace);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SimpleCard instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.exercicekafka3.model.SimpleCard other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.spades)) {
        this.spades = data().deepCopy(fields()[0].schema(), other.spades);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ace)) {
        this.ace = data().deepCopy(fields()[1].schema(), other.ace);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'spades' field.
      * the spades
      * @return The value.
      */
    public java.lang.CharSequence getSpades() {
      return spades;
    }

    /**
      * Sets the value of the 'spades' field.
      * the spades
      * @param value The value of 'spades'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.SimpleCard.Builder setSpades(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.spades = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'spades' field has been set.
      * the spades
      * @return True if the 'spades' field has been set, false otherwise.
      */
    public boolean hasSpades() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'spades' field.
      * the spades
      * @return This builder.
      */
    public com.example.exercicekafka3.model.SimpleCard.Builder clearSpades() {
      spades = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ace' field.
      * the card number
      * @return The value.
      */
    public java.lang.CharSequence getAce() {
      return ace;
    }

    /**
      * Sets the value of the 'ace' field.
      * the card number
      * @param value The value of 'ace'.
      * @return This builder.
      */
    public com.example.exercicekafka3.model.SimpleCard.Builder setAce(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ace = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ace' field has been set.
      * the card number
      * @return True if the 'ace' field has been set, false otherwise.
      */
    public boolean hasAce() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ace' field.
      * the card number
      * @return This builder.
      */
    public com.example.exercicekafka3.model.SimpleCard.Builder clearAce() {
      ace = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SimpleCard build() {
      try {
        SimpleCard record = new SimpleCard();
        record.spades = fieldSetFlags()[0] ? this.spades : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ace = fieldSetFlags()[1] ? this.ace : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SimpleCard>
    WRITER$ = (org.apache.avro.io.DatumWriter<SimpleCard>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SimpleCard>
    READER$ = (org.apache.avro.io.DatumReader<SimpleCard>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
